[workspace]
name = "eigenpy"
version = "3.12.0"
description = "Bindings between Numpy and Eigen using Boost.Python"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
channels = ["conda-forge"]
license = "BSD-2-Clause"
license-file = "LICENSE"
preview = ["pixi-build"]

[dependencies]
ccache = ">=4.9.1"
cmake = ">=3.10"
cxx-compiler = ">=1.7.0"
ninja = ">=1.11"
pkg-config = ">=0.29.2"
git = ">=2.47.0"
libboost-devel = ">=1.80.0"
libboost-python-devel = ">=1.80.0"
eigen = ">=3.4.0"
numpy = ">=1.22.0"
python = ">=3.9.0"
scipy = ">=1.10.0"

[package]
name = { workspace = true }
version = { workspace = true }

[package.build]
backend = { name = "pixi-build-cmake", version = "0.3.*" }

[package.build.config]
extra-args = [
  "-DGENERATE_PYTHON_STUBS=ON",
  "-DBUILD_TESTING=OFF",
  "-DBUILD_TESTING_SCIPY=OFF",
]

[package.build-dependencies]
pkg-config = ">=0.29.2"

[package.host-dependencies]
libboost-devel = ">=1.80.0"
libboost-python-devel = ">=1.80.0"
eigen = ">=3.4.0"
numpy = ">=1.22.0"
scipy = ">=1.10.0"
python = ">=3.9.0"

[package.run-dependencies]
scipy = ">=1.10.0"

[target.unix.activation]
scripts = ["development/scripts/pixi/activation.sh"]

[target.win-64.activation]
scripts = ["development/scripts/pixi/activation.bat"]

[activation.env]
# Setup ccache
CMAKE_CXX_COMPILER_LAUNCHER = "ccache"
# Create compile_commands.json for language server
CMAKE_EXPORT_COMPILE_COMMANDS = "ON"
# Activate color output with Ninja
CMAKE_COLOR_DIAGNOSTICS = "ON"

[tasks]
# We must avoid to set CMAKE_CXX_FLAGS because of WIN32
# https://discourse.cmake.org/t/strictly-appending-to-cmake-lang-flags/6478
configure = { args = [
  { arg = "build_dir", default = "build" },
  { arg = "build_type", default = "$EIGENPY_BUILD_TYPE" },
  { arg = "python_stubs", default = "$EIGENPY_PYTHON_STUBS" },
  { arg = "cholmod_support", default = "$EIGENPY_CHOLMOD_SUPPORT" },
  { arg = "accelerate_support", default = "$EIGENPY_ACCELERATE_SUPPORT" },
], cmd = [
  "CXXFLAGS=$EIGENPY_CXX_FLAGS",
  "cmake",
  "-G",
  "Ninja",
  "-B",
  "{{ build_dir }}",
  "-S",
  ".",
  "-DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX",
  "-DCMAKE_BUILD_TYPE={{ build_type }}",
  "-DGENERATE_PYTHON_STUBS={{ python_stubs }}",
  "-DBUILD_WITH_CHOLMOD_SUPPORT={{ cholmod_support }}",
  "-DBUILD_WITH_ACCELERATE_SUPPORT={{ accelerate_support }}",
] }
build = { cmd = "cmake --build build --target all", depends-on = ["configure"] }
clean = { cmd = "rm -rf build" }
test = { cmd = "ctest --test-dir build --output-on-failure", depends-on = [
  "build",
] }

[feature.lint]
dependencies = { pre-commit = ">=3.6.2" }
tasks = { lint = { cmd = "pre-commit run --all" } }

# Increment the version number with EIGENPY_VERSION variable
[feature.new-version.dependencies]
tomlkit = ">=0.13.2"

[feature.new-version.tasks]
release-new-version = { cmd = "VERSION=$EIGENPY_VERSION cmake --build build_new_version --target release", depends-on = [
  { task = "configure", args = [
    { build_type = "Release" },
    { build_dir = "build_new_version" },
    { python_stubs = "ON" },
    { accelerate_support = "OFF" },
    { cholmod_support = "ON" },
  ] },
] }

# Cholmod support
[feature.cholmod]
dependencies = { suitesparse = ">=5" }
activation = { env = { EIGENPY_CHOLMOD_SUPPORT = "ON" } }

# Accelerate only work on Apple ARMÂ platform
[feature.accelerate]
[feature.accelerate.target.osx-arm64]
activation = { env = { EIGENPY_ACCELERATE_SUPPORT = "ON" } }

[feature.python-latest.dependencies]
python = "3.14.*"

[feature.python-oldest.dependencies]
python = "3.10.*"

# Use clang-cl on Windows
[feature.clang-cl]
platforms = ["win-64"]
activation = { env = { CC = "clang-cl", CXX = "clang-cl" } }
dependencies = { clangxx = "*" }

# Use clang on GNU/Linux
[feature.clang]
platforms = ["linux-64"]
activation = { env = { CC = "clang", CXX = "clang++" } }
dependencies = { clangxx = "*" }

[environments]
default = { features = ["python-latest"], solve-group = "python-latest" }
clang = { features = ["clang", "python-latest"] }
lint = { features = ["lint"], solve-group = "python-latest" }
cholmod = { features = [
  "cholmod",
  "python-latest",
], solve-group = "python-latest" }
accelerate = { features = [
  "accelerate",
  "python-latest",
], solve-group = "python-latest" }
python-oldest = { features = ["python-oldest"], solve-group = "python-oldest" }
# Accelerate will only work in Eigen next release
all = { features = ["cholmod", "python-latest"], solve-group = "python-latest" }
all-python-oldest = { features = [
  "cholmod",
  "python-oldest",
], solve-group = "python-oldest" }
all-clang-cl = { features = [
  "cholmod",
  "clang-cl",
  "python-latest",
], solve-group = "python-latest" }
# Release a new software version
new-version = { features = [
  "new-version",
  "cholmod",
  "python-latest",
], solve-group = "python-latest" }
